### ISSUE TITLE
bundler: failed to load command: middleman (/usr/local/bundle/bin/middleman)

### ISSUE THREAD

**Issue by saiprasannasastry** [hashicorp/terraform-website#1099]
i am trying to test my provider website and getting the below error,
i am able to ping to releases.hashicorp.com

```
which bundle --version =
Bundler version 1.16.6,
gem --version
2.5.1
```
```
sudo make website
==> Starting website in Docker...
== The Middleman is loading
bundler: failed to load command: middleman (/usr/local/bundle/bin/middleman)
SocketError: Failed to open TCP connection to releases.hashicorp.com:443 (getaddrinfo: Try again)
  /usr/local/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
  /usr/local/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
  /usr/local/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
  /usr/local/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
  /usr/local/lib/ruby/2.3.0/net/http.rb:878:in `connect'
  /usr/local/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
  /usr/local/lib/ruby/2.3.0/net/http.rb:852:in `start'
  /usr/local/lib/ruby/2.3.0/open-uri.rb:319:in `open_http'
  /usr/local/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
  /usr/local/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
  /usr/local/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
  /usr/local/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
  /usr/local/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
  /usr/local/lib/ruby/2.3.0/open-uri.rb:717:in `open'
  /usr/local/lib/ruby/2.3.0/open-uri.rb:35:in `open'
  /usr/local/bundle/gems/middleman-hashicorp-0.3.41/lib/middleman-hashicorp/releases.rb:10:in `fetch'
  /usr/local/bundle/gems/middleman-hashicorp-0.3.41/lib/middleman-hashicorp/extension.rb:291:in `product_versions'
  /usr/local/bundle/gems/middleman-hashicorp-0.3.41/lib/middleman-hashicorp/extension.rb:56:in `initialize'
  /usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/extensions.rb:122:in `new'
  /usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/extensions.rb:122:in `activate'
  /website/config.rb:3:in `initialize'
  /usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/extensions.rb:162:in `instance_eval'
  /usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/extensions.rb:162:in `initialize'
  /usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/data.rb:31:in `initialize'
  /usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/application.rb:213:in `initialize'
  /usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/request.rb:56:in `new'
  /usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/request.rb:56:in `inst'
  /usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/preview_server.rb:132:in `new_app'
  /usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/preview_server.rb:31:in `start'
  /usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/cli/server.rb:89:in `server'
  /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/cli.rb:72:in `method_missing'
  /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:29:in `run'
  /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:128:in `run'
  /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /usr/local/bundle/gems/middleman-core-3.4.1/lib/middleman-core/cli.rb:20:in `start'
  /usr/local/bundle/gems/middleman-core-3.4.1/bin/middleman:18:in `<top (required)>'
  /usr/local/bundle/bin/middleman:23:in `load'
  /usr/local/bundle/bin/middleman:23:in `<top (required)>'
Makefile:20: recipe for target 'website' failed
make: *** [website] Error 1

```

**Comment by paddycarver** [comment]
Is this running without internet connection or behind a firewall?

` Failed to open TCP connection to releases.hashicorp.com:443`

Seems to be the relevant line in that issue trace.

**Comment by nfagerlund** [comment]
The thing that looks up releases to build the download page could really use a softer failure mode, so people can preview the website when offline. (This has bitten me a few times on airplanes, etc.)

But, our middleman platform is also on borrowed time, so it's sort of a race: will we fix this before abandoning the platform entirely? Prooobably not.

**Comment by laurapacilio** [comment]
Hi all - I'm going to close this out, as we are definitely now moving away from the middleman platform that was the subject of this ticket. We expect to make a switch in the next few months. But please reopen if still needed!
